### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sergioandresco** [flexydemy/php-user-authentification#1]
https://github.com/flexydemy/php-user-authentification/blob/fb8fbf577107ed87b124fa169ba9e84d3fc171f8/src/controller/Controller.php#L117

In case of wanting to encrypt the password of the user to register, how could it be done?, and when logging in, how should it be decrypted?

**Comment by mystroken** [comment]
Hello,
You can use `password_hash` function to encrypt the password at the registering. Then `password_verify` function to verify if a given string matches the stored encrypted password.

[password_hash()](https://www.php.net/manual/en/function.password-hash.php)
[password_verify()](https://www.php.net/manual/en/function.password-verify.php)

**Comment by sergioandresco** [comment]
Oh amaizing, thank you

**Comment by mystroken** [comment]
You're welcome mate!
So I'm going to close this issue.
